"""add subscribe check column

Revision ID: 19cb887fcc07
Revises: 258c7c0a2724
Create Date: 2014-04-23 19:55:19.582461

"""

# revision identifiers, used by Alembic.
revision = '19cb887fcc07'
down_revision = '258c7c0a2724'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscribe_confirm', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscribe_confirm')
    ### end Alembic commands ###
