"""empty message

Revision ID: 1c5cdb0a116c
Revises: 8f03d1816e8
Create Date: 2014-05-19 06:52:19.754000

"""

# revision identifiers, used by Alembic.
revision = '1c5cdb0a116c'
down_revision = '8f03d1816e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    ### end Alembic commands ###
