"""empty message

Revision ID: 28188d1c21b1
Revises: None
Create Date: 2014-07-14 00:45:40.143554

"""

# revision identifiers, used by Alembic.
revision = '28188d1c21b1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
