"""empty message

Revision ID: 2a9761f1c3da
Revises: 38f26f12b2c2
Create Date: 2014-07-15 00:08:39.532601

"""

# revision identifiers, used by Alembic.
revision = '2a9761f1c3da'
down_revision = '38f26f12b2c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscribed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscribed')
    ### end Alembic commands ###
