"""empty message

Revision ID: 304973796976
Revises: 30ffdafdc8e9
Create Date: 2014-09-28 18:31:42.921788

"""

# revision identifiers, used by Alembic.
revision = '304973796976'
down_revision = '30ffdafdc8e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('judged', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'judged')
    ### end Alembic commands ###
