"""empty message

Revision ID: 30ffdafdc8e9
Revises: 19b8f19646f1
Create Date: 2014-09-28 18:08:52.332650

"""

# revision identifiers, used by Alembic.
revision = '30ffdafdc8e9'
down_revision = '19b8f19646f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('submission', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'team', ['submission'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team')
    op.drop_column('team', 'submission')
    ### end Alembic commands ###
