"""empty message

Revision ID: 3268362937fc
Revises: c000d1899f8
Create Date: 2014-10-22 20:50:33.350615

"""

# revision identifiers, used by Alembic.
revision = '3268362937fc'
down_revision = 'c000d1899f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('hide', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'hide')
    ### end Alembic commands ###
