"""empty message

Revision ID: 32ffe9d926a0
Revises: 39dae00846a1
Create Date: 2014-06-27 00:52:48.272023

"""

# revision identifiers, used by Alembic.
revision = '32ffe9d926a0'
down_revision = '39dae00846a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.BOOLEAN(), nullable=False))
    ### end Alembic commands ###
