"""empty message

Revision ID: 39dae00846a1
Revises: 566e37a7a20b
Create Date: 2014-06-27 00:39:02.752349

"""

# revision identifiers, used by Alembic.
revision = '39dae00846a1'
down_revision = '566e37a7a20b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
