"""empty message

Revision ID: 476d684b7d2b
Revises: 1dfffabf47d6
Create Date: 2014-08-31 23:51:13.287100

"""

# revision identifiers, used by Alembic.
revision = '476d684b7d2b'
down_revision = '1dfffabf47d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
