"""empty message

Revision ID: 4bbff4404799
Revises: 36b3cd04687f
Create Date: 2014-07-20 17:33:58.340163

"""

# revision identifiers, used by Alembic.
revision = '4bbff4404799'
down_revision = '36b3cd04687f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
