"""empty message

Revision ID: 5107996b3876
Revises: 4bbff4404799
Create Date: 2014-09-01 00:37:24.828307

"""

# revision identifiers, used by Alembic.
revision = '5107996b3876'
down_revision = '4bbff4404799'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('endorsement', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'user', sa.Column('intro', sa.Text(), nullable=True))
    op.add_column(u'user', sa.Column('location', sa.String(length=20), nullable=True))
    op.add_column(u'user', sa.Column('major', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'major')
    op.drop_column(u'user', 'location')
    op.drop_column(u'user', 'intro')
    op.drop_table('idea')
    ### end Alembic commands ###
