"""empty message

Revision ID: 55d42b06122c
Revises: 5107996b3876
Create Date: 2014-09-01 15:46:43.049046

"""

# revision identifiers, used by Alembic.
revision = '55d42b06122c'
down_revision = '5107996b3876'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('comp_status', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('request_teammate', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'request_teammate')
    op.drop_column('team', 'comp_status')
    ### end Alembic commands ###
