"""empty message

Revision ID: 566e37a7a20b
Revises: 2a57f0e2e897
Create Date: 2014-05-20 18:43:26.153384

"""

# revision identifiers, used by Alembic.
revision = '566e37a7a20b'
down_revision = '2a57f0e2e897'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'user', ['avatar'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user')
    op.drop_column('user', 'avatar')
    ### end Alembic commands ###
