"""empty message

Revision ID: 8f03d1816e8
Revises: 445f73cbd2ac
Create Date: 2014-05-19 06:42:21.390528

"""

# revision identifiers, used by Alembic.
revision = '8f03d1816e8'
down_revision = '445f73cbd2ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
